### ISSUE TITLE
Consider enabling CI

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/opentelemetry-java-instrumentation#1]
```yaml
version: 2.1

commands:
  setup_build_environment:
    description: "Checkout, restore the cache, and setup docker"
    steps:
      - checkout

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx1g
      TERM: dumb
    steps:
      - setup_build_environment
      - run: ls $JAVA_HOME/bin
      - run: rmic || true
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> $BASH_ENV
      - run:
          command: ./gradlew check --stacktrace -x :smoke-tests:test
          no_output_timeout: 30m

  release-bintray-publish:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - setup_build_environment
      - run: echo "Releasing version" && ./gradlew printVersion
      - run: ./gradlew publish


workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release-bintray-publish:
          context: hypertrace-publishing
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
```
